<?php
/* $tp_id=$this->tp_id;
 echo "<p>Id=".$tp_id."</p>";
 if($this->tp_record === NULL)
 {
 	echo "not found";
 }
 else
 {
	//echo "<pre>".print_r($this->tp_record,true)."</pre>";
	echo "Template-name: »".$this->escape($this->tp_record->name)."«";
 }
 
 $output ="";
 */
 echo "test".$tp_id;
 $fp = @fopen($this->tp_reccord->name, "r") or die ("Could not open file");
     while($line = fgets($fp, 1024)){
     $output = $output.$line;
     }
     fclose($fp);
     
     echo $ouput;
 
 
  ?>
