<?php

  function createWithList($doSave, $fields, $userinput)
  {
  	if($doSave)
  	{   
  		foreach ($userinput as $keyoutput => $output )
		{
//			echo $keyoutput.": ";
//			echo $output."<br>";			
        echo $keyoutput.": ".$userinput["$keyoutput"]."<br>";
		}

//        echo $keyoutput.": ".$userinput["test"]."<br>";
		return $userinput;
  	}
  	
    else
    {
  		echo "<br><form name=\"formular\" method=\"post\">";
  		
  		foreach($fields as $output )
  		{
  		  echo $output->name.":<br><input type=\"text\" name=\"".$output->name."\" value=\"\"><br>";
  		}
  		echo "<br><input type=\"submit\" name=\"submitbutton\" \" value=\"Generate\"> </form>";
  		return 0;
    }
  }
  
 
  $withList = createWithList(isset($this->iarray['submitbutton']),$this->placeholders, $this->ppost);
  		echo "<a href=\"".$this->url(array('controller'=>'template'),'default', true).">Back</a>";
  
?>

