<?php

  function inputData($doSave, $fields)
  {
   	
  	if($doSave)
  	{
  		foreach($fields as $output)
  			echo $output."<br>";
  	  return $fields;	
  	}
  	
  	else
  	{
  		$count = 0;
  		echo "<form name=\"formular\" method=\"post\">";
  		
  		foreach($fields as $key => $output )
  		{
  			echo $key.":<br><input type=\"text\" name=\"pFirst".$count++."\" value=\"".$output. "\"><br>";
  		}
  		echo "<br><input type=\"submit\" name=\"submitbutton\" \" value=\"Generate\"> </form>";
  	}
  }
  
  
  
  inputData(isset($this->iarray['submitbutton'])
  					, $this->ppost
  					);  
?>

