<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>ShirleyTemplate</title>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
  <?php echo $this->headLink()->appendStylesheet('/css/menu_style.css') ?>
  <?php echo $this->headLink()->appendStylesheet('/css/982558.css') ?>

</head>

<body>
<div id="pagewidth" >

<div id="header">
    <!-- <img src="/Images/banner_bg1.png" height="80"; width="100%"; alt="Logo Shirley Template" ></img>	<!-- bg -->
    <img src="/Images/st_logo.png" class="logo"; height="80"; alt="Logo Shirley Template" ></img>	<!-- logo -->        
</div>



<div id="wrapper" class="clearfix">
			<div id="maincol">
			<ul class="menu">
<li class="top"><a href="" target="_self" class="top_link"><span>Template</span></a>
<ul class="sub">
<li><a href="<?php echo $this->url(array('controller'=>'template'),'default', true) ?>" target="_self">Choose your Template</a></li>
<li><a href="<?php echo $this->url(array('controller'=>'template'),'default',true) ?>" target="_self">Delete a Template</a></li>
</ul>
</li>
<?php 
        	$auth = Zend_Auth::getInstance();
        	if($auth->hasIdentity())
        	{
        ?>
<li class="top"><a href="<?php echo $this->url(array('controller'=>'account','action'=>'logout'),'default',true) ?>" target="_self" class="top_link" id="logout"><span>Logout</span></a>
</li>
<?php 
        	} else {
       ?>
<li class="top"><a href="<?php echo $this->url(
       array('controller'=>'account','action'=>'login'),
       'default',
        true) ?>" id="login" target="_self" class="top_link"><span>Login</span></a>
</li>
<li class="top"><a href="<?php echo $this->url(
       array('controller'=>'account','action'=>'register'),
       'default',
       true) ?>" id="register" target="_self" class="top_link"><span>Register</span></a>
</li>
   <?php }?>
</ul>
			
			
			<?php echo $this->layout()->content ?>
			</div>
	</div>
	<div id="footer">
		<p>Copyright by Team 7</p>
	</div>
	</div>


</body>
</html>
