<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>ShirleyTemplate</title>
<?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
<?php echo $this->headLink()->appendStylesheet('/css/menu_style.css') ?>
<?php echo $this->headLink()->appendStylesheet('/css/982558.css') ?>
<?php echo $this->headLink()->appendStylesheet('/css/dark-hive/jquery-ui-1.8.13.custom.css') ?>
<?php echo $this->jQuery(); ?>
</head>

<body>
	<div id="pagewidth">
		<div id="header"></div>
		<div id="wrapper" class="clearfix">
			<div id="maincol">
				<ul class="menu">
					<li class="top"><a href="" target="_self" class="top_link"
						id="Template-Menu"><span>Template</span> </a>
						<ul class="sub">
							<li><a
								href="<?php echo $this->url(array('controller'=>'template'),'default', true) ?>"
								target="_self" id="Choose-Template">Create new Template</a></li>
							<li><a
								href="<?php echo $this->url(array('controller'=>'template', 'action'=>'reuseview'),'default',true) ?>"
								target="_self" id="Reuse-Template">Reuse old Templates</a></li>
						</ul>
					</li>
					<?php
					$auth = Zend_Auth::getInstance();
					if($auth->hasIdentity())
					{
						?>
					<li class="top"><a href="" target="_self" class="top_link"
						id="Profile-Menu"><span>Profile</span> </a>
						<ul class="sub">
							<li><a
								href="<?php echo $this->url(array('controller'=>'account', 'action'=> 'editprofile'),'default', true) ?>"
								target="_self" id="Edit-Profile">Edit your Profile</a></li>
						</ul>
					</li>

					<li class="top"><a
						href="<?php echo $this->url(array('controller'=>'account','action'=>'logout'),'default',true) ?>"
						target="_self" class="top_link" id="logout"><span>Logout</span> </a>
					</li>
					<?php
					} else {
						?>
					<li class="top"><a
						href="<?php echo $this->url(array('controller'=>'account','action'=>'login'),'default',true) ?>"
						id="login" target="_self" class="top_link"><span>Login</span> </a>
					</li>
					<li class="top"><a
						href="<?php echo $this->url(array('controller'=>'account','action'=>'register'),'default',true) ?>"
						id="register" target="_self" class="top_link"><span>Register</span>
					</a>
					</li>
					<?php }?>
				</ul>
				<div id="contentdata">
					<?php echo $this->layout()->content ?>
				</div>
			</div>
		</div>
		<div id="footer">
			&copy; 2011 by Team 7
		</div>
	</div>
</body>
</html>
