<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>ShirleyTemplate</title>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>

</head>



<body>
<div id="header" style="background-color: #A0B0FF; height: 80px;">
    <div id="header-logo" style="float: left">
    <img src="Images/test.jpg" height="80px" ></img>
    </div>
    
    <div id="header-navigation" style="position: absolute; top:50px; left:100px;">
    

<ul id="menu">
<li><span>Template</span>
<dl>
	<dt><a href="">
	Template</a></dt>
	<dd><a href="<?php echo $this->url(array('controller'=>'template'),'default', true) ?>">
	Create
	</a></dd>
	<dd><a href="<?php echo $this->url(array('controller'=>'template'),'default',true) ?>">Delete</a></dd>
	<dd><a href="../mozilla/content.html">Download</a></dd>
</dl>
</li>

<li><span>...</span>
<dl>
	<dt><a href="">...</a></dt>
		<dd><a href="<?php echo $this->url(array('controller'=>'template'),'default', true) ?>">
        ...
        </a></dd>
	<dd><a href="../application/controllers/GuestbookController.php">...</a></dd>
	<dd><a href="../mozilla/content.html">...</a></dd>
</dl>
</li>

<li><span>...</span>
<dl>
	<dt><a href="">...</a></dt>
		<dd><a href="<?php echo $this->url(array('controller'=>'template'),'default', true) ?>">
        ...
        </a></dd>
	<dd><a href="../mozilla/cascade.html">...</a></dd>
	<dd><a href="../mozilla/content.html">...</a></dd>
</dl>
</li>  
</ul>  
    
    
     </div>
    
    <div id="header-user" style="position:absolute; right: 2%; top:60px;">
       <a href="<?php echo $this->url(
       array('controller'=>'guestbook'),
       'default',
        true) ?>"id="login">Login</a>
       <a href="<?php echo $this->url(
       array('controller'=>'guestbook'),
       'default',
       true) ?>"id="register">Register</a>
        
    </div>
</div>




<?php echo $this->layout()->content ?>

</body>
</html>
